# Generated by Django 5.2.5 on 2026-09-24 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='kind',
            field=models.CharField(choices=[('PAYMENT_VERIFIED', 'Payment verified'), ('PROCESSING_STARTED', 'Processing started'), ('NEEDS_ATTENTION', 'Needs attention'), ('ORDER_READY', 'Order ready'), ('PAYMENT_REJECTED', 'Payment rejected'), ('OCR_COMPLETED', 'OCR completed'), ('OCR_FAILED', 'OCR failed'), ('REVIEW_REQUIRED', 'Review required'), ('EXPORT_READY', 'Export ready'), ('SYSTEM', 'System')], db_index=True, max_length=40),
        ),
    ]
