import json


def generate_apps_script(*, job_id, form_id, mappings, responses, classification):
    config = {
        "formId": form_id,
        "datasetId": str(job_id),
        "classification": classification,
        "responsesPerExecution": 40,
    }
    config_json = json.dumps(config, ensure_ascii=False, separators=(",", ":"))
    mappings_json = json.dumps(mappings, ensure_ascii=False, separators=(",", ":"))
    responses_json = json.dumps(responses, ensure_ascii=False, separators=(",", ":"))
    banner = (
        "SYNTHETIC DATA — NOT HUMAN RESEARCH RESPONSES"
        if classification.startswith("SYNTHETIC")
        else "CONFIRMED DIGITIZED HUMAN RESPONSES"
    )
    return f'''/**
 * Generated by ScanToForms.
 * DATA CLASSIFICATION: {banner}
 *
 * Before submitting anything:
 *   1. Run previewMapping() and inspect the execution log.
 *   2. Confirm that every Google Form item title and item type is correct.
 *   3. Run startSubmission(). For large datasets, run continueSubmission()
 *      repeatedly until submissionStatus() reports complete.
 *
 * The script remembers submitted response IDs in Script Properties, so normal
 * reruns do not intentionally submit the same ScanToForms record twice.
 */

const STF_CONFIG = Object.freeze({config_json});
const STF_MAPPINGS = Object.freeze({mappings_json});
const STF_RESPONSES = Object.freeze({responses_json});

function normalizeTitle_(value) {{
  return String(value || '').trim().replace(/\\s+/g, ' ').toLowerCase();
}}

function formItemsByTitle_(form) {{
  const indexed = {{}};
  form.getItems().forEach((item) => {{
    const key = normalizeTitle_(item.getTitle());
    if (!key) return;
    if (indexed[key]) {{
      throw new Error(`The Google Form contains duplicate item titles: "${{item.getTitle()}}". Rename them so every mapped title is unique.`);
    }}
    indexed[key] = item;
  }});
  return indexed;
}}

function mappedItems_(form) {{
  const byTitle = formItemsByTitle_(form);
  const mapped = {{}};
  Object.keys(STF_MAPPINGS).forEach((questionKey) => {{
    const targetTitle = STF_MAPPINGS[questionKey];
    if (!targetTitle) return;
    const item = byTitle[normalizeTitle_(targetTitle)];
    if (!item) {{
      throw new Error(`No Google Form item matches "${{targetTitle}}" (ScanToForms key: ${{questionKey}}).`);
    }}
    mapped[questionKey] = item;
  }});
  return mapped;
}}

function previewMapping() {{
  const form = FormApp.openById(STF_CONFIG.formId);
  const mapped = mappedItems_(form);
  console.log(`Data classification: ${{STF_CONFIG.classification}}`);
  console.log(`Form: ${{form.getTitle()}}`);
  console.log(`Responses waiting: ${{STF_RESPONSES.length}}`);
  Object.keys(mapped).forEach((key) => {{
    console.log(`${{key}} -> ${{mapped[key].getTitle()}} [${{mapped[key].getType()}}]`);
  }});
  return {{ formTitle: form.getTitle(), responseCount: STF_RESPONSES.length, mappedQuestions: Object.keys(mapped).length }};
}}

function hasValue_(value) {{
  if (value === null || value === undefined) return false;
  if (Array.isArray(value)) return value.length > 0;
  return String(value).trim() !== '';
}}

function asArray_(value) {{
  return Array.isArray(value) ? value.map(String) : [String(value)];
}}

function asGridArray_(value) {{
  if (Array.isArray(value)) return value.map(String);
  if (value && typeof value === 'object') return Object.values(value).map(String);
  return [String(value)];
}}

function asCheckboxGridArray_(value) {{
  if (Array.isArray(value)) return value.map((row) => Array.isArray(row) ? row.map(String) : [String(row)]);
  if (value && typeof value === 'object') return Object.values(value).map((row) => Array.isArray(row) ? row.map(String) : [String(row)]);
  return [[String(value)]];
}}

function createItemResponse_(item, value) {{
  switch (item.getType()) {{
    case FormApp.ItemType.TEXT:
      return item.asTextItem().createResponse(String(value));
    case FormApp.ItemType.PARAGRAPH_TEXT:
      return item.asParagraphTextItem().createResponse(String(value));
    case FormApp.ItemType.MULTIPLE_CHOICE:
      return item.asMultipleChoiceItem().createResponse(String(value));
    case FormApp.ItemType.CHECKBOX:
      return item.asCheckboxItem().createResponse(asArray_(value));
    case FormApp.ItemType.LIST:
      return item.asListItem().createResponse(String(value));
    case FormApp.ItemType.SCALE:
      return item.asScaleItem().createResponse(Number(value));
    case FormApp.ItemType.RATING:
      return item.asRatingItem().createResponse(Number(value));
    case FormApp.ItemType.DATE:
      return item.asDateItem().createResponse(new Date(String(value)));
    case FormApp.ItemType.DATETIME:
      return item.asDateTimeItem().createResponse(new Date(String(value)));
    case FormApp.ItemType.TIME: {{
      const parts = String(value).split(':').map(Number);
      return item.asTimeItem().createResponse(parts[0], parts[1] || 0);
    }}
    case FormApp.ItemType.DURATION: {{
      const parts = String(value).split(':').map(Number);
      return item.asDurationItem().createResponse(parts[0] || 0, parts[1] || 0, parts[2] || 0);
    }}
    case FormApp.ItemType.GRID:
      return item.asGridItem().createResponse(asGridArray_(value));
    case FormApp.ItemType.CHECKBOX_GRID:
      return item.asCheckboxGridItem().createResponse(asCheckboxGridArray_(value));
    default:
      throw new Error(`Unsupported Google Forms item type for "${{item.getTitle()}}": ${{item.getType()}}`);
  }}
}}

function cursorKey_() {{
  return `stf:${{STF_CONFIG.datasetId}}:cursor`;
}}

function submittedKey_(responseId) {{
  return `stf:${{STF_CONFIG.datasetId}}:submitted:${{responseId}}`;
}}

function startSubmission() {{
  previewMapping();
  return continueSubmission();
}}

function continueSubmission() {{
  const lock = LockService.getScriptLock();
  if (!lock.tryLock(10000)) throw new Error('Another submission run is still active. Try again shortly.');
  try {{
    const form = FormApp.openById(STF_CONFIG.formId);
    if (!form.isAcceptingResponses()) throw new Error('The Google Form is not accepting responses.');
    const mapped = mappedItems_(form);
    const properties = PropertiesService.getScriptProperties();
    let cursor = Number(properties.getProperty(cursorKey_()) || 0);
    const stop = Math.min(cursor + STF_CONFIG.responsesPerExecution, STF_RESPONSES.length);
    let submitted = 0;
    let skipped = 0;

    for (; cursor < stop; cursor += 1) {{
      const record = STF_RESPONSES[cursor];
      if (properties.getProperty(submittedKey_(record.id))) {{
        skipped += 1;
        properties.setProperty(cursorKey_(), String(cursor + 1));
        continue;
      }}
      const formResponse = form.createResponse();
      Object.keys(mapped).forEach((questionKey) => {{
        const value = record.answers[questionKey];
        if (!hasValue_(value)) return;
        formResponse.withItemResponse(createItemResponse_(mapped[questionKey], value));
      }});
      formResponse.submit();
      properties.setProperty(submittedKey_(record.id), new Date().toISOString());
      properties.setProperty(cursorKey_(), String(cursor + 1));
      submitted += 1;
    }}

    const remaining = Math.max(STF_RESPONSES.length - cursor, 0);
    const result = {{ submitted, skipped, cursor, remaining, complete: remaining === 0 }};
    console.log(JSON.stringify(result));
    if (remaining > 0) console.log('Run continueSubmission() again to submit the next group.');
    return result;
  }} finally {{
    lock.releaseLock();
  }}
}}

function submissionStatus() {{
  const cursor = Number(PropertiesService.getScriptProperties().getProperty(cursorKey_()) || 0);
  const result = {{
    classification: STF_CONFIG.classification,
    processed: Math.min(cursor, STF_RESPONSES.length),
    total: STF_RESPONSES.length,
    remaining: Math.max(STF_RESPONSES.length - cursor, 0),
    complete: cursor >= STF_RESPONSES.length,
  }};
  console.log(JSON.stringify(result));
  return result;
}}
'''

