# Generated by Django 5.2.5 on 2026-09-01 00:35

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('questionnaires', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BotRun',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('requested_responses', models.PositiveIntegerField()),
                ('generated_responses', models.PositiveIntegerField(default=0)),
                ('seed', models.PositiveBigIntegerField()),
                ('status', models.CharField(choices=[('QUEUED', 'Queued'), ('PROCESSING', 'Processing'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed')], db_index=True, default='QUEUED', max_length=16)),
                ('error_message', models.TextField(blank=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bot_runs', to=settings.AUTH_USER_MODEL)),
                ('questionnaire_version', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bot_runs', to='questionnaires.questionnaireversion')),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='SyntheticResponse',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('sequence', models.PositiveIntegerField()),
                ('answers', models.JSONField(default=dict)),
                ('data_label', models.CharField(default='SYNTHETIC DATA — NOT A HUMAN RESEARCH RESPONSE', max_length=80)),
                ('run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responses', to='botlab.botrun')),
            ],
            options={
                'ordering': ('sequence',),
                'constraints': [models.UniqueConstraint(fields=('run', 'sequence'), name='unique_synthetic_run_sequence')],
            },
        ),
    ]
