# Generated by Django 5.2.5 on 2026-09-24 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('botlab', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='syntheticresponse',
            name='data_label',
            field=models.CharField(default='SYNTHETIC TEST DATA — NOT A HUMAN RESEARCH RESPONSE', max_length=80),
        ),
    ]
