# Generated by Django 5.2.5 on 2026-09-24 16:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('botlab', '0001_initial'),
        ('googleforms', '0001_initial'),
        ('questionnaires', '0003_reviewed_answer_integrity'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.CharField(editable=False, max_length=30, null=True, unique=True)),
                ('title', models.CharField(max_length=255)),
                ('service_type', models.CharField(choices=[('DIGITIZATION', 'Questionnaire digitization'), ('SYNTHETIC_DATA', 'Synthetic TEST data')], max_length=20)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('UPLOADING', 'Uploading'), ('AWAITING_PAYMENT', 'Awaiting payment'), ('PAYMENT_SUBMITTED', 'Payment submitted'), ('PAID', 'Paid'), ('QUEUED', 'Queued'), ('PROCESSING', 'Processing'), ('NEEDS_REVIEW', 'Needs attention'), ('READY', 'Ready'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed'), ('CANCELLED', 'Cancelled')], db_index=True, default='DRAFT', max_length=24)),
                ('respondent_count', models.PositiveIntegerField(default=0)),
                ('pages_per_respondent', models.PositiveIntegerField(default=1)),
                ('question_count', models.PositiveIntegerField(default=0)),
                ('expected_page_count', models.PositiveIntegerField(default=0)),
                ('synthetic_response_count', models.PositiveIntegerField(default=0)),
                ('instructions', models.TextField(blank=True)),
                ('google_form_url', models.CharField(blank=True, max_length=500)),
                ('google_form_id', models.CharField(blank=True, max_length=180)),
                ('amount_ngn', models.DecimalField(decimal_places=2, max_digits=12)),
                ('pricing_snapshot', models.JSONField(default=dict)),
                ('payment_method', models.CharField(default='BANK_TRANSFER', editable=False, max_length=24)),
                ('payment_status', models.CharField(choices=[('UNPAID', 'Unpaid'), ('SUBMITTED', 'Submitted for verification'), ('VERIFIED', 'Verified'), ('REJECTED', 'Rejected')], default='UNPAID', max_length=16)),
                ('payment_sender_name', models.CharField(blank=True, max_length=180)),
                ('payment_reference', models.CharField(blank=True, max_length=180)),
                ('payment_claimed_at', models.DateTimeField(blank=True, null=True)),
                ('payment_verified_at', models.DateTimeField(blank=True, null=True)),
                ('payment_rejection_reason', models.TextField(blank=True)),
                ('operator_notes', models.TextField(blank=True)),
                ('processing_started_at', models.DateTimeField(blank=True, null=True)),
                ('ready_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('apps_script_job', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='order', to='googleforms.appsscriptjob')),
                ('bot_run', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='order', to='botlab.botrun')),
                ('payment_verified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='verified_orders', to=settings.AUTH_USER_MODEL)),
                ('questionnaire', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='order', to='questionnaires.questionnaire')),
                ('response_batch', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='order', to='questionnaires.responsebatch')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='orders', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='OrderEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=80)),
                ('from_status', models.CharField(blank=True, max_length=24)),
                ('to_status', models.CharField(blank=True, max_length=24)),
                ('note', models.TextField(blank=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='events', to='orders.order')),
            ],
            options={
                'ordering': ('created_at', 'id'),
            },
        ),
        migrations.AddConstraint(
            model_name='order',
            constraint=models.CheckConstraint(condition=models.Q(('amount_ngn__gt', 0)), name='order_positive_amount'),
        ),
        migrations.AddConstraint(
            model_name='order',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('respondent_count__gt', 0), ('response_batch__isnull', False), ('service_type', 'DIGITIZATION'), ('synthetic_response_count', 0)), models.Q(('respondent_count', 0), ('response_batch__isnull', True), ('service_type', 'SYNTHETIC_DATA'), ('synthetic_response_count__gt', 0)), _connector='OR'), name='order_service_consistency'),
        ),
        migrations.AddConstraint(
            model_name='order',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('payment_status', 'VERIFIED'), ('payment_verified_at__isnull', False), ('payment_verified_by__isnull', False)), models.Q(models.Q(('payment_status', 'VERIFIED'), _negated=True), ('payment_verified_at__isnull', True), ('payment_verified_by__isnull', True)), _connector='OR'), name='order_payment_consistency'),
        ),
    ]
