# Generated by Django 5.2.5 on 2026-09-01 00:35

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PaystackEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payload_hash', models.CharField(max_length=64, unique=True)),
                ('event_type', models.CharField(db_index=True, max_length=80)),
                ('received_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(choices=[('FREE', 'Free'), ('STUDENT', 'Student Pro'), ('RESEARCHER', 'Researcher Pro'), ('ORGANIZATION', 'Organization')], max_length=24, unique=True)),
                ('name', models.CharField(max_length=80)),
                ('description', models.TextField(blank=True)),
                ('monthly_price_kobo', models.PositiveIntegerField(default=0)),
                ('yearly_price_kobo', models.PositiveIntegerField(blank=True, null=True)),
                ('monthly_page_limit', models.PositiveIntegerField()),
                ('monthly_bot_lab_runs', models.PositiveIntegerField(default=0)),
                ('batch_size_limit', models.PositiveIntegerField(default=1)),
                ('max_team_members', models.PositiveSmallIntegerField(default=1)),
                ('has_xlsx', models.BooleanField(default=False)),
                ('has_google_forms', models.BooleanField(default=False)),
                ('has_advanced_exports', models.BooleanField(default=False)),
                ('has_analytics', models.BooleanField(default=False)),
                ('priority_processing', models.BooleanField(default=False)),
                ('contact_required', models.BooleanField(default=False)),
                ('is_public', models.BooleanField(default=True)),
                ('display_order', models.PositiveSmallIntegerField(default=0)),
            ],
            options={
                'ordering': ('display_order',),
            },
        ),
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=180)),
                ('owner', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='owned_organization', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PaymentTransaction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('product', models.CharField(choices=[('SUBSCRIPTION', 'Subscription'), ('EXTRA_PAGES', '100 extra OCR pages')], max_length=20)),
                ('billing_cycle', models.CharField(blank=True, choices=[('MONTHLY', 'Monthly'), ('YEARLY', 'Yearly')], max_length=12)),
                ('reference', models.CharField(max_length=100, unique=True)),
                ('amount_kobo', models.PositiveIntegerField()),
                ('currency', models.CharField(default='NGN', max_length=3)),
                ('status', models.CharField(choices=[('INITIALIZED', 'Initialized'), ('SUCCESS', 'Successful'), ('FAILED', 'Failed')], db_index=True, default='INITIALIZED', max_length=16)),
                ('authorization_url', models.URLField(blank=True, max_length=500)),
                ('access_code', models.CharField(blank=True, max_length=120)),
                ('paystack_id', models.CharField(blank=True, max_length=80)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('gateway_response', models.JSONField(blank=True, default=dict)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payment_transactions', to=settings.AUTH_USER_MODEL)),
                ('plan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='payments', to='billing.plan')),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('billing_cycle', models.CharField(choices=[('MONTHLY', 'Monthly'), ('YEARLY', 'Yearly')], max_length=12)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('PAST_DUE', 'Past due'), ('CANCELLED', 'Cancelled'), ('EXPIRED', 'Expired')], db_index=True, default='ACTIVE', max_length=16)),
                ('current_period_start', models.DateTimeField()),
                ('current_period_end', models.DateTimeField(db_index=True)),
                ('cancel_at_period_end', models.BooleanField(default=False)),
                ('paystack_customer_code', models.CharField(blank=True, max_length=80)),
                ('paystack_subscription_code', models.CharField(blank=True, max_length=80)),
                ('paystack_email_token', models.CharField(blank=True, max_length=160)),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='subscriptions', to='billing.plan')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='subscription', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='OrganizationMembership',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('role', models.CharField(choices=[('OWNER', 'Owner'), ('MEMBER', 'Member')], default='MEMBER', max_length=12)),
                ('is_active', models.BooleanField(default=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='billing.organization')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='organization_membership', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('organization', 'user'), name='unique_organization_user')],
            },
        ),
        migrations.CreateModel(
            name='UsageRecord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('month', models.DateField()),
                ('pages_used', models.PositiveIntegerField(default=0)),
                ('extra_pages', models.PositiveIntegerField(default=0)),
                ('bot_lab_runs_used', models.PositiveIntegerField(default=0)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='monthly_usage', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-month',),
                'constraints': [models.UniqueConstraint(fields=('account', 'month'), name='unique_account_usage_month')],
            },
        ),
    ]
