# Generated by Django 5.2.5 on 2026-09-01 05:35

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('botlab', '0001_initial'),
        ('questionnaires', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AppsScriptJob',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('source_type', models.CharField(choices=[('RESPONSE_BATCH', 'Confirmed human responses'), ('BOT_RUN', 'Bot Lab synthetic responses')], max_length=24)),
                ('form_id', models.CharField(max_length=180)),
                ('mappings', models.JSONField(default=dict)),
                ('script', models.TextField()),
                ('response_count', models.PositiveIntegerField()),
                ('data_classification', models.CharField(max_length=100)),
                ('batch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='apps_script_jobs', to='questionnaires.responsebatch')),
                ('bot_run', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='apps_script_jobs', to='botlab.botrun')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='apps_script_jobs', to=settings.AUTH_USER_MODEL)),
                ('questionnaire_version', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='apps_script_jobs', to='questionnaires.questionnaireversion')),
            ],
            options={
                'ordering': ('-created_at',),
                'constraints': [models.CheckConstraint(condition=models.Q(models.Q(('batch__isnull', False), ('bot_run__isnull', True)), models.Q(('batch__isnull', True), ('bot_run__isnull', False)), _connector='OR'), name='apps_script_exactly_one_source')],
            },
        ),
    ]
