# Generated by Django 5.2.5 on 2026-08-26 21:48

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Questionnaire',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('READY', 'Ready'), ('ARCHIVED', 'Archived')], db_index=True, default='DRAFT', max_length=20)),
                ('source_language', models.CharField(default='en', max_length=12)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questionnaires', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='QuestionnaireVersion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('version_number', models.PositiveIntegerField()),
                ('parse_status', models.CharField(choices=[('DRAFT', 'Draft'), ('VALID', 'Valid'), ('NEEDS_REVIEW', 'Needs review')], default='DRAFT', max_length=20)),
                ('parser_version', models.CharField(blank=True, max_length=80)),
                ('raw_schema', models.JSONField(blank=True, default=dict)),
                ('questionnaire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='questionnaires.questionnaire')),
            ],
            options={
                'ordering': ('-version_number',),
            },
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('key', models.CharField(max_length=80)),
                ('position', models.PositiveIntegerField()),
                ('text', models.TextField()),
                ('help_text', models.TextField(blank=True)),
                ('type', models.CharField(choices=[('SHORT_TEXT', 'Short answer'), ('PARAGRAPH', 'Paragraph'), ('SINGLE_CHOICE', 'Single choice'), ('MULTIPLE_CHOICE', 'Multiple choice'), ('DROPDOWN', 'Dropdown'), ('LIKERT', 'Likert scale'), ('LINEAR_SCALE', 'Linear scale'), ('SINGLE_GRID', 'Multiple-choice grid'), ('MULTIPLE_GRID', 'Checkbox grid'), ('DATE', 'Date'), ('TIME', 'Time'), ('NUMBER', 'Number')], max_length=24)),
                ('required', models.BooleanField(default=False)),
                ('validation_rules', models.JSONField(blank=True, default=dict)),
                ('source_region', models.JSONField(blank=True, default=dict)),
                ('version', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='questionnaires.questionnaireversion')),
            ],
            options={
                'ordering': ('position',),
            },
        ),
        migrations.CreateModel(
            name='QuestionOption',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('key', models.CharField(max_length=80)),
                ('label', models.CharField(max_length=500)),
                ('position', models.PositiveIntegerField()),
                ('value', models.CharField(blank=True, max_length=500)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options', to='questionnaires.question')),
            ],
            options={
                'ordering': ('position',),
            },
        ),
        migrations.CreateModel(
            name='Response',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('respondent_reference', models.CharField(blank=True, max_length=120)),
                ('status', models.CharField(choices=[('PROCESSING', 'Processing'), ('NEEDS_REVIEW', 'Needs review'), ('CONFIRMED', 'Confirmed'), ('REJECTED', 'Rejected'), ('FAILED', 'Failed')], db_index=True, default='PROCESSING', max_length=20)),
                ('confirmed_at', models.DateTimeField(blank=True, null=True)),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_responses', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('created_at',),
            },
        ),
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('value_text', models.TextField(blank=True)),
                ('value_json', models.JSONField(blank=True, default=dict)),
                ('confidence', models.DecimalField(blank=True, decimal_places=4, max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1)])),
                ('review_status', models.CharField(choices=[('AUTO_HIGH', 'High confidence'), ('AUTO_MEDIUM', 'Medium confidence'), ('NEEDS_REVIEW', 'Needs review'), ('CORRECTED', 'Corrected'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], default='NEEDS_REVIEW', max_length=20)),
                ('source_region', models.JSONField(blank=True, default=dict)),
                ('raw_value', models.JSONField(blank=True, default=dict)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='answers', to='questionnaires.question')),
                ('response', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='questionnaires.response')),
            ],
            options={
                'ordering': ('question__position',),
            },
        ),
        migrations.CreateModel(
            name='ResponseBatch',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('PROCESSING', 'Processing'), ('NEEDS_REVIEW', 'Needs review'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed')], db_index=True, default='DRAFT', max_length=20)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='response_batches', to=settings.AUTH_USER_MODEL)),
                ('questionnaire_version', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='batches', to='questionnaires.questionnaireversion')),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
        migrations.AddField(
            model_name='response',
            name='batch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responses', to='questionnaires.responsebatch'),
        ),
        migrations.AddConstraint(
            model_name='questionnaireversion',
            constraint=models.UniqueConstraint(fields=('questionnaire', 'version_number'), name='unique_questionnaire_version'),
        ),
        migrations.AddConstraint(
            model_name='question',
            constraint=models.UniqueConstraint(fields=('version', 'key'), name='unique_question_key_per_version'),
        ),
        migrations.AddConstraint(
            model_name='question',
            constraint=models.UniqueConstraint(fields=('version', 'position'), name='unique_question_position_per_version'),
        ),
        migrations.AddConstraint(
            model_name='questionoption',
            constraint=models.UniqueConstraint(fields=('question', 'key'), name='unique_option_key_per_question'),
        ),
        migrations.AddConstraint(
            model_name='questionoption',
            constraint=models.UniqueConstraint(fields=('question', 'position'), name='unique_option_position_per_question'),
        ),
        migrations.AddConstraint(
            model_name='answer',
            constraint=models.UniqueConstraint(fields=('response', 'question'), name='unique_answer_per_response_question'),
        ),
    ]
