# Generated by Django 5.2.5 on 2026-09-01 12:22

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


def backfill_response_grouping(apps, schema_editor):
    ResponseBatch = apps.get_model("questionnaires", "ResponseBatch")
    for batch in ResponseBatch.objects.select_related("questionnaire_version").iterator():
        for sequence, response in enumerate(batch.responses.order_by("created_at", "id"), start=1):
            response.sequence = sequence
            response.expected_page_count = batch.questionnaire_version.expected_page_count
            response.save(update_fields=("sequence", "expected_page_count"))


class Migration(migrations.Migration):

    dependencies = [
        ('questionnaires', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TemplatePage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('page_number', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)])),
                ('reference_text', models.TextField(blank=True)),
                ('anchors', models.JSONField(blank=True, default=list)),
                ('text_signature', models.CharField(blank=True, max_length=64)),
            ],
            options={
                'ordering': ('page_number',),
            },
        ),
        migrations.AlterModelOptions(
            name='response',
            options={'ordering': ('sequence', 'created_at')},
        ),
        migrations.AddField(
            model_name='question',
            name='template_page_number',
            field=models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AddField(
            model_name='questionnaireversion',
            name='expected_page_count',
            field=models.PositiveIntegerField(default=1, help_text='Number of physical pages in one complete questionnaire response.', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AddField(
            model_name='response',
            name='expected_page_count',
            field=models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AddField(
            model_name='response',
            name='sequence',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='response',
            name='validation_issues',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name='response',
            name='status',
            field=models.CharField(choices=[('UPLOADING', 'Uploading'), ('INCOMPLETE', 'Incomplete'), ('READY_FOR_PROCESSING', 'Ready for processing'), ('PROCESSING', 'Processing'), ('NEEDS_REVIEW', 'Needs review'), ('CONFIRMED', 'Confirmed'), ('REJECTED', 'Rejected'), ('FAILED', 'Failed')], db_index=True, default='UPLOADING', max_length=24),
        ),
        migrations.RunPython(backfill_response_grouping, migrations.RunPython.noop),
        migrations.AddConstraint(
            model_name='response',
            constraint=models.UniqueConstraint(fields=('batch', 'sequence'), name='unique_response_sequence_per_batch'),
        ),
        migrations.AddField(
            model_name='templatepage',
            name='version',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='template_pages', to='questionnaires.questionnaireversion'),
        ),
        migrations.AddConstraint(
            model_name='templatepage',
            constraint=models.UniqueConstraint(fields=('version', 'page_number'), name='unique_template_page_per_version'),
        ),
    ]
