# Generated by Django 5.2.5 on 2026-09-24 16:13

from django.conf import settings
from django.db import migrations, models


def normalize_existing(apps, schema_editor):
    Response = apps.get_model("questionnaires", "Response")
    Answer = apps.get_model("questionnaires", "Answer")
    Response.objects.filter(status="CONFIRMED", confirmed_at__isnull=True).update(status="NEEDS_REVIEW", reviewed_by=None)
    Response.objects.exclude(status="CONFIRMED").update(confirmed_at=None, reviewed_by=None)
    Answer.objects.filter(review_status="CORRECTED").update(provenance="MANUAL")
    Answer.objects.filter(review_status="APPROVED").update(provenance="APPROVED")


class Migration(migrations.Migration):

    dependencies = [
        ('questionnaires', '0002_templatepage_alter_response_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='provenance',
            field=models.CharField(choices=[('OCR', 'OCR'), ('MANUAL', 'Human correction'), ('APPROVED', 'Human approved')], default='OCR', max_length=12),
        ),
        migrations.RunPython(normalize_existing, migrations.RunPython.noop),
        migrations.AddConstraint(
            model_name='response',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('confirmed_at__isnull', False), ('status', 'CONFIRMED')), models.Q(models.Q(('status', 'CONFIRMED'), _negated=True), ('confirmed_at__isnull', True)), _connector='OR'), name='response_confirmation_consistent'),
        ),
    ]
