# Generated by Django 5.2.5 on 2026-09-01 00:35

from django.db import migrations, models


def normalize_removed_roles(apps, schema_editor):
    User = apps.get_model("accounts", "User")
    User.objects.filter(role__in=("PRO", "COMPANY")).update(role="USER")


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(normalize_removed_roles, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('USER', 'Normal user'), ('RESEARCHER', 'Researcher'), ('ADMIN', 'Administrator')], db_index=True, default='USER', max_length=20),
        ),
    ]
