# Generated by Django 5.2.5 on 2026-08-26 21:48

import apps.documents.models
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('questionnaires', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentPage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('page_number', models.PositiveIntegerField()),
                ('width', models.PositiveIntegerField(blank=True, null=True)),
                ('height', models.PositiveIntegerField(blank=True, null=True)),
                ('preprocessing', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'ordering': ('page_number',),
            },
        ),
        migrations.CreateModel(
            name='OCRJob',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('QUEUED', 'Queued'), ('PROCESSING', 'Processing'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed'), ('NEEDS_REVIEW', 'Needs review')], db_index=True, default='QUEUED', max_length=20)),
                ('engine', models.CharField(blank=True, max_length=80)),
                ('model_version', models.CharField(blank=True, max_length=120)),
                ('attempts', models.PositiveSmallIntegerField(default=0)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('processing_ms', models.PositiveIntegerField(blank=True, null=True)),
                ('error_code', models.CharField(blank=True, max_length=80)),
                ('error_message', models.TextField(blank=True)),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='ExtractionResult',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('parser_version', models.CharField(max_length=80)),
                ('confidence', models.DecimalField(blank=True, decimal_places=4, max_digits=5, null=True)),
                ('structured_output', models.JSONField(blank=True, default=dict)),
                ('warnings', models.JSONField(blank=True, default=list)),
                ('job', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='extraction', to='documents.ocrjob')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='OCRResult',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('plain_text', models.TextField(blank=True)),
                ('mean_confidence', models.DecimalField(blank=True, decimal_places=4, max_digits=5, null=True)),
                ('raw_output', models.JSONField(blank=True, default=dict)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='documents.ocrjob')),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ocr_results', to='documents.documentpage')),
            ],
        ),
        migrations.CreateModel(
            name='OCRRegion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('sequence', models.PositiveIntegerField()),
                ('kind', models.CharField(default='text', max_length=40)),
                ('text', models.TextField(blank=True)),
                ('confidence', models.DecimalField(blank=True, decimal_places=4, max_digits=5, null=True)),
                ('bounding_box', models.JSONField(default=dict)),
                ('result', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='regions', to='documents.ocrresult')),
            ],
            options={
                'ordering': ('sequence',),
            },
        ),
        migrations.CreateModel(
            name='UploadedDocument',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('document_type', models.CharField(choices=[('TEMPLATE', 'Blank questionnaire template'), ('RESPONSE', 'Completed questionnaire')], max_length=20)),
                ('file', models.FileField(max_length=500, upload_to=apps.documents.models.secure_upload_path)),
                ('original_filename', models.CharField(max_length=255)),
                ('content_type', models.CharField(max_length=100)),
                ('size_bytes', models.PositiveBigIntegerField()),
                ('sha256', models.CharField(db_index=True, max_length=64)),
                ('page_count', models.PositiveIntegerField(default=1)),
                ('status', models.CharField(choices=[('UPLOADED', 'Uploaded'), ('QUEUED', 'Queued'), ('PROCESSING', 'Processing'), ('COMPLETED', 'Completed'), ('NEEDS_REVIEW', 'Needs review'), ('FAILED', 'Failed'), ('DELETED', 'Deleted')], db_index=True, default='UPLOADED', max_length=20)),
                ('failure_reason', models.TextField(blank=True)),
                ('batch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='questionnaires.responsebatch')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='uploaded_documents', to=settings.AUTH_USER_MODEL)),
                ('questionnaire', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='questionnaires.questionnaire')),
                ('response', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documents', to='questionnaires.response')),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
        migrations.AddField(
            model_name='ocrjob',
            name='document',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ocr_job', to='documents.uploadeddocument'),
        ),
        migrations.AddField(
            model_name='documentpage',
            name='document',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pages', to='documents.uploadeddocument'),
        ),
        migrations.AddConstraint(
            model_name='ocrresult',
            constraint=models.UniqueConstraint(fields=('job', 'page'), name='unique_ocr_result_per_job_page'),
        ),
        migrations.AddConstraint(
            model_name='ocrregion',
            constraint=models.UniqueConstraint(fields=('result', 'sequence'), name='unique_ocr_region_sequence'),
        ),
        migrations.AddIndex(
            model_name='uploadeddocument',
            index=models.Index(fields=['owner', 'sha256'], name='documents_u_owner_i_329ea4_idx'),
        ),
        migrations.AddConstraint(
            model_name='documentpage',
            constraint=models.UniqueConstraint(fields=('document', 'page_number'), name='unique_document_page'),
        ),
    ]
