# Generated by Django 5.2.5 on 2026-09-01 12:22

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


def backfill_document_pages(apps, schema_editor):
    DocumentPage = apps.get_model("documents", "DocumentPage")
    UploadedDocument = apps.get_model("documents", "UploadedDocument")
    QuestionnaireVersion = apps.get_model("questionnaires", "QuestionnaireVersion")
    OCRResult = apps.get_model("documents", "OCRResult")

    completed_page_ids = set(OCRResult.objects.values_list("page_id", flat=True))
    for page in DocumentPage.objects.select_related("document", "document__response").iterator():
        page.response_id = page.document.response_id
        page.original_upload_order = page.page_number
        page.assigned_template_page_number = page.page_number if page.response_id else None
        page.classification_method = "UPLOAD_ORDER" if page.response_id else "UNCLASSIFIED"
        if page.response_id:
            expected = page.document.response.expected_page_count
            page.classification_confidence = 0.95 if page.document.page_count == expected else 0.55
        page.processing_status = "COMPLETED" if page.id in completed_page_ids else "PENDING"
        page.save(
            update_fields=(
                "response",
                "original_upload_order",
                "assigned_template_page_number",
                "classification_method",
                "classification_confidence",
                "processing_status",
            )
        )

    templates = UploadedDocument.objects.filter(document_type="TEMPLATE", questionnaire_id__isnull=False)
    for document in templates.iterator():
        version = QuestionnaireVersion.objects.filter(questionnaire_id=document.questionnaire_id).order_by("-version_number").first()
        if version and version.expected_page_count != document.page_count:
            version.expected_page_count = document.page_count
            version.save(update_fields=("expected_page_count",))


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0001_initial'),
        ('questionnaires', '0002_templatepage_alter_response_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='documentpage',
            options={'ordering': ('assigned_template_page_number', 'original_upload_order', 'page_number')},
        ),
        migrations.AddField(
            model_name='documentpage',
            name='assigned_template_page_number',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='documentpage',
            name='classification_confidence',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1)]),
        ),
        migrations.AddField(
            model_name='documentpage',
            name='classification_method',
            field=models.CharField(choices=[('UNCLASSIFIED', 'Unclassified'), ('UPLOAD_ORDER', 'Provisional upload order'), ('PAGE_MARKER', 'Printed page marker'), ('TEXT_SIMILARITY', 'Template text similarity'), ('MANUAL', 'Manual assignment'), ('QR_CODE', 'QR code')], default='UNCLASSIFIED', max_length=24),
        ),
        migrations.AddField(
            model_name='documentpage',
            name='detected_template_page_number',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='documentpage',
            name='original_upload_order',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='documentpage',
            name='processing_status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('PROCESSING', 'Processing'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed')], default='PENDING', max_length=16),
        ),
        migrations.AddField(
            model_name='documentpage',
            name='response',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pages', to='questionnaires.response'),
        ),
        migrations.AddField(
            model_name='documentpage',
            name='validation_issues',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='uploadeddocument',
            name='grouping_mode',
            field=models.CharField(choices=[('PDF_PER_RESPONSE', 'One PDF per respondent'), ('MANUAL_RESPONSE', 'Manual respondent pages'), ('BULK_ORDERED', 'Bulk images in respondent order'), ('TEMPLATE', 'Questionnaire template')], default='PDF_PER_RESPONSE', max_length=24),
        ),
        migrations.RunPython(backfill_document_pages, migrations.RunPython.noop),
        migrations.AddIndex(
            model_name='documentpage',
            index=models.Index(fields=['response', 'assigned_template_page_number'], name='documents_d_respons_b79711_idx'),
        ),
    ]
