# Generated by Django 5.2.5 on 2026-09-24 16:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0002_alter_documentpage_options_and_more'),
        ('orders', '0001_initial'),
        ('questionnaires', '0003_reviewed_answer_integrity'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadeddocument',
            name='order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='uploads', to='orders.order'),
        ),
        migrations.AddField(
            model_name='uploadeddocument',
            name='upload_key',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddConstraint(
            model_name='uploadeddocument',
            constraint=models.UniqueConstraint(fields=('order', 'upload_key'), name='unique_order_upload_key'),
        ),
    ]
