# Generated by Django 5.2.17 on 2026-09-25 16:12

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0003_uploadeddocument_order_uploadeddocument_upload_key_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='StorageDeletion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=500)),
                ('storage_signature', models.CharField(max_length=64)),
                ('attempts', models.PositiveIntegerField(default=0)),
                ('error_code', models.CharField(blank=True, max_length=100)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='ocrjob',
            name='execution_token',
            field=models.UUIDField(blank=True, editable=False, null=True),
        ),
    ]
